spring.application.name=edueasy-config
server.port=8888

# ⚠️ ACTIVER LE MODE NATIVE
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config-repo

# Désactiver la sécurité pour le test
spring.security.basic.enabled=false
management.security.enabled=false

# Logging
logging.level.org.springframework.cloud.config=DEBUG